name: test

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  TestMatrix:
    strategy:
      matrix:
        lua-version: ["5.1", "5.2", "5.3", "5.4", "luajit"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: hishamhm/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.lua-version }}

    - uses: hishamhm/gh-actions-luarocks@master
      with:
        luaRocksVersion: "3.11.1"

    - name: Prep
      run: |
        luarocks install busted
        luarocks install busted-htest
        luarocks make

    - name: Tests
      run: |
        busted -o htest
